name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
          cache-dependency-path: './mitech-website/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
        working-directory: ./mitech-website
      
      - name: Build Next.js app
        run: npm run build
        working-directory: ./mitech-website
        env:
          NODE_ENV: production
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./mitech-website/out
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
